# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = "yoyo's blog"
copyright = '2022, yoyo'
author = 'yoyo'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["ablog", "sphinx_sitemap"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_TW'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'press'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static', 'feed.xml', 'robots.txt']

html_extra_path = ["feed.xml", "robots.txt"]

html_css_files = ["css/style.css"]

html_baseurl = 'https://yoyoleetw.github.io'

sitemap_filename = "sitemap.xml"

blog_authors = {
    "yoyoLeeTW": ("Yo-Yo Li", "https://github.com/yoyoLeeTW"),
}
blog_default_author = "yoyoLeeTW"
blog_languages = {
    "en": ("English", None),
    "zh": ("中文", None),
}
blog_locations = {
    "TW": ("Taiwan", None),
}
blog_baseurl = "https://yoyoleetw.github.io"
blog_title = "yoyo's Blog"
blog_path = "blog"

blog_feed_archives = True

fontawesome_link_cdn = "https://pro.fontawesome.com/releases/v5.13.0/css/all.css"
fontawesome_included = True

# disqus_shortname = ""
