name: deploy-blog

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Build the site
        run: |
          pipenv run make html

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
